[package]
name = "trace_rs"
version = "0.1.0"
authors = ["philipp.welsch"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
