[package]
name = "trace_rs"
version = "0.1.0"
links="armffi"
build="build.rs"
authors = ["philipp.welsch"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
rand = "0.8.1"

[profile.release]
debug = 1